lora:
  rank: [32, 64, 128]
  alpha: 16
dora:
  rank: [32, 64, 128]
  alpha: 16
plora:
  rank: [32, 64, 128]
  alpha: 16
vera:
  rank: 256
  lr: [0.001, 0.0001, 0.00001]
  alpha: 16
pvera:
  rank: 256
  lr: [0.001, 0.0001, 0.00001]
  alpha: 16
adaptformer:
  reduction_ratios: [4, 8, 16]
  activation: ReLU
bottleneck:
  reduction_ratios: [4, 8, 16]
  activation: ReLU
ia3: None